# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/eoan64"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
   end

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade -y
     apt-get install -y youtube-dl
     apt-get install -y ffmpeg
     apt-get install -y vim
     apt-get install -y git
     git clone https://github.com/alexzywiak/youtube-transcriber.git
   SHELL

end
