# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade -y
     wget https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
     tar -C /usr/local -xzf go1.14.4.linux-amd64.tar.gz
     export PATH=$PATH:/usr/local/go/bin
     echo "export PATH=$PATH:/usr/local/go/bin" >> .profile
   SHELL
end
