# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "droidmlwr/Xenial64"
  config.vm.hostname = "VGWDET1"


  # Timeout after 10 minutes
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  # Disable default local file share
  config.vm.synced_folder ".", "/vagrant", disbled: true

  # Private Network: vboxnet0 192.168.0.1/24 DHCP .254 [30 ADDR].20-.50
  config.vm.network "private_network", ip: "192.168.0.100", name: "vboxnet0"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "3060"
     
   end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get -y upgrade
     apt-get -y install libffi-dev
     apt-get -y install libfuzzy-dev
     apt-get -y install net-tools
     apt-get -y install python
     apt-get -y install python-dev
     apt-get -y install python-pip
     pip install --upgrade pip
     pip install ssdeep
     pip install pefile
   SHELL
end
