# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
 
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update && upgrade -y
     apt-get install -y vim
     apt-get -y install python-pip
     wget -qO- https://get.docker.com/ | sh
     sudo usermod -aG docker $(whoami)
     sudo pip install docker-compose
   SHELL
end
