# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # general provisioning
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network"

  # virtualbox provisioning
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

    # SHELL PROVISIONING
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update && upgrade -y
     apt-get install -y vim
     apt-get -y install python-pip
     shell.args "wget -qO- https://get.docker.com/ | sh"
     sudo usermod -aG docker $(whoami)
     sudo pip install docker-compose
   SHELL

end
