# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.3.5"
Vagrant.configure("2") do |config|

  # general provisioning
  config.vm.boot_timeout = 600
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  config.vm.hostname = "BionicDocker"
  config.vm.network = "public_network"

  # virtualbox provisioning using VBox Manage
  config.vm.provider "virtualbox" do |vb|
    v.gui = false
    v.cpus = 2
    v.memory = 2048
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    v.customize [""]
  end

    # SHELL PROVISIONING
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update && upgrade -y
     apt-get install -y vim
     apt-get -y install python-pip
     echo "This is an Ubuntu 18.04 LTS box built for use with Docker!"
   SHELL

#   shell.args "wget -qO- https://get.docker.com/ | sh"
#   sudo usermod -aG docker $(whoami)
#   sudo pip install docker-compose

end
