# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# Current Errors
#[default] No Virtualbox Guest Additions installation found.


Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/eoan64"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "4098"
   end

   # $0 is a path to shared dir on the host machine, $1 is absolute path of shared guest machine dir
   config.vm.synced_folder "/home/shiny/Documents/github/vagrant-cookbook/virtualbox/ubuntu_htb/sync", "/tmp/sync", create: true

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade
     sudo apt-get install openvpn -y
     sudo apt-get install binwalk -y
     sudo apt-get install make -y
     sudo apt-get install unzip -y
     git clone https://github.com/radare/radare2.git
     chmod +x radare2/sys/install.sh
     ./radare2/sys/install.sh

   SHELL
end
